dependencies:

  - name: kube-state-metrics
    version: "2.8.*"
    #repository: https://kubernetes-charts.storage.googleapis.com/
    repository: "file://charts/kube-state-metrics"
    condition: kubeStateMetrics.enabled

  - name: prometheus-node-exporter
    version: "1.10.*"
    #repository: https://kubernetes-charts.storage.googleapis.com/
    repository: "file://charts/prometheus-node-exporter"
    condition: nodeExporter.enabled

  - name: grafana
    version: "5.1.*"
    #repository: https://kubernetes-charts.storage.googleapis.com/
    repository: "file://charts/grafana"
    condition: grafana.enabled
